CREATE TABLE Customers (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(50),
    Age NUMBER,
    Balance NUMBER,
    IsVIP VARCHAR2(5)
);


CREATE TABLE Loans (
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    InterestRate NUMBER,
    DueDate DATE
);



INSERT INTO Customers VALUES (1, 'Chandu', 65, 15000, 'FALSE');
INSERT INTO Customers VALUES (2, 'Raju', 45, 5000, 'FALSE');
INSERT INTO Customers VALUES (3, 'Pavan', 70, 25000, 'FALSE');
INSERT INTO Customers VALUES (4, 'Harsha', 35, 12000, 'FALSE');



INSERT INTO Loans VALUES (101, 1, 10, SYSDATE + 20);
INSERT INTO Loans VALUES (102, 2, 12, SYSDATE + 40);
INSERT INTO Loans VALUES (103, 3, 9, SYSDATE + 15);
INSERT INTO Loans VALUES (104, 4, 11, SYSDATE + 25);

COMMIT;



SELECT * FROM Customers;
SELECT * FROM Loans;